"""Added Date of Birth and Name to Credential

Revision ID: 13599ad493af
Revises: 3a2e0ab5dd8e
Create Date: 2022-01-09 08:13:17.498709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13599ad493af'
down_revision = '3a2e0ab5dd8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential', sa.Column('firstname', sa.String(), nullable=False))
    op.add_column('credential', sa.Column('lastname', sa.String(), nullable=False))
    op.add_column('credential', sa.Column('date_of_birth', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credential', 'date_of_birth')
    op.drop_column('credential', 'lastname')
    op.drop_column('credential', 'firstname')
    # ### end Alembic commands ###
