"""Added Unique Constraint for Country Name

Revision ID: 1a4df9476ed0
Revises: 6aa795fbf6ae
Create Date: 2022-01-07 10:59:49.389748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4df9476ed0'
down_revision = '6aa795fbf6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'country', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='unique')
    # ### end Alembic commands ###
