"""Added Confirmation Code Field on Credential

Revision ID: 3a2e0ab5dd8e
Revises: 690a29487c41
Create Date: 2022-01-09 06:25:27.070186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2e0ab5dd8e'
down_revision = '690a29487c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('confirmation_code', sa.String(), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('challenge', sa.String(), nullable=False),
    sa.Column('reset_required', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('account', sa.Column('credential_id', sa.Integer(), nullable=False))
    op.drop_constraint('account_email_key', 'account', type_='unique')
    op.create_unique_constraint(None, 'account', ['credential_id'])
    op.create_foreign_key(None, 'account', 'credential', ['credential_id'], ['id'])
    op.drop_column('account', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_constraint(None, 'account', type_='unique')
    op.create_unique_constraint('account_email_key', 'account', ['email'])
    op.drop_column('account', 'credential_id')
    op.drop_table('credential')
    # ### end Alembic commands ###
