"""Changed User Refs to Account

Revision ID: 6aa795fbf6ae
Revises: f294b63bcdcf
Create Date: 2022-01-07 09:59:09.140577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa795fbf6ae'
down_revision = 'f294b63bcdcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_constraint('team_user_id_key', 'team', type_='unique')
    op.create_unique_constraint(None, 'team', ['account_id'])
    op.drop_constraint('team_user_id_fkey', 'team', type_='foreignkey')
    op.create_foreign_key(None, 'team', 'account', ['account_id'], ['id'])
    op.drop_column('team', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_foreign_key('team_user_id_fkey', 'team', 'account', ['user_id'], ['id'])
    op.drop_constraint(None, 'team', type_='unique')
    op.create_unique_constraint('team_user_id_key', 'team', ['user_id'])
    op.drop_column('team', 'account_id')
    # ### end Alembic commands ###
