"""Added Unique Constraint for Position Name

Revision ID: 80bdc90879e6
Revises: 1a4df9476ed0
Create Date: 2022-01-07 13:25:56.632350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80bdc90879e6'
down_revision = '1a4df9476ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'position', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'position', type_='unique')
    # ### end Alembic commands ###
