"""Set Account Active as Mandatory

Revision ID: 845998a331bd
Revises: b6a9dce93191
Create Date: 2022-01-08 11:35:56.336428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845998a331bd'
down_revision = 'b6a9dce93191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
