"""Added Role Configuration

Revision ID: 9cfea4e300f7
Revises: 40d905352a3f
Create Date: 2022-01-11 10:32:37.027426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfea4e300f7'
down_revision = '40d905352a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'credential', ['role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credential', type_='unique')
    op.drop_column('credential', 'role_id')
    # ### end Alembic commands ###
