"""Corrected Transfer To Team Foreign Key

Revision ID: a93c37d952f8
Revises: 13599ad493af
Create Date: 2022-01-09 15:26:27.350160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93c37d952f8'
down_revision = '13599ad493af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'active')
    op.add_column('credential', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_constraint('transfer_to_team_id_fkey', 'transfer', type_='foreignkey')
    op.create_foreign_key(None, 'transfer', 'team', ['to_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.create_foreign_key('transfer_to_team_id_fkey', 'transfer', 'player', ['to_team_id'], ['id'])
    op.drop_column('credential', 'active')
    op.add_column('account', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
