"""Removed Unique Constraint on Role-Id

Revision ID: c29b45a3c1ed
Revises: f19e250465c1
Create Date: 2022-01-13 07:20:06.879504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29b45a3c1ed'
down_revision = 'f19e250465c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('credential_role_id_key', 'credential', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('credential_role_id_key', 'credential', ['role_id'])
    # ### end Alembic commands ###
