"""Added nickname

Revision ID: cff73a5252ee
Revises: 9cfea4e300f7
Create Date: 2022-01-11 18:15:34.313128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff73a5252ee'
down_revision = '9cfea4e300f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('nickname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'nickname')
    # ### end Alembic commands ###
